name: Go (posix-pattern)

on:
  push:
    branches: [ main ]
  pull_request:

permissions: {}

jobs:
  go:
    uses: openconfig/common-ci/.github/workflows/basic_go.yml@f7481cbcc8395277a2393aee3a2a0b3b7f3516a6
    permissions:
      contents: read
      packages: read
      # To report Github Actions status checks
      statuses: write
